version: '3.3'
services:
  swagger-ui:
    ports:
      - '8080:8080'
    environment:
      - SWAGGER_JSON=/swagger/swagger.json
      - SUPPORTED_SUBMIT_METHODS=[] # disable "try it out"
    volumes:
      - './swagger:/swagger'
    image: swaggerapi/swagger-ui
